In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats
import re
import sys 
import statsmodels.stats.multitest
#sys.path.append('C:\\Users\\brittany\\henderson\\GitHub\\GBM_for_CPTAC\\')
#import cis_functions as f
#sys.path.append('C:\\Users\\Lindsey\\Documents\\GitHub\\WhenMutationsDontMatter\\')
#import plot_utils as p


import cptac
import cptac.utils as u

# GBM

In [2]:

df = pd.read_csv('GBM_EGFR_all.csv')
df = df.drop(['Unnamed: 0'], axis=1)
df

     Comparison     Slope     R_squared       P_value
0          GRB2 -0.163726  4.115691e-01  5.651892e-14
1          SOX9  0.248300  2.735875e-01  5.382478e-09
2        CDKN2C  0.275173  2.362861e-01  8.399510e-08
3          GAB1  0.142447  2.154911e-01  3.690040e-07
4           DBI  0.181830  2.136181e-01  4.209130e-07
...         ...       ...           ...           ...
1067     RASAL1 -0.001428  3.994018e-06  9.835452e-01
1068      ERBB4  0.000347  6.814417e-07  9.932029e-01
1069      ABCB1 -0.000186  2.624149e-07  9.957820e-01
1070   TNFSF13B  0.000256  6.799018e-07  9.972472e-01
1071       FZD7  0.000114  5.478364e-08  9.980727e-01

[1072 rows x 4 columns]

# Kidney

In [3]:
df2 = pd.read_csv('Kidney_EGFR_all.csv')

In [4]:
df2 = df2.drop(['Unnamed: 0'], axis=1)
df2

     Comparison     Slope  R_squared       P_value
0          LDHA  1.314776   0.837644  1.006123e-77
1          PFKP  2.427952   0.828691  1.749218e-75
2           HK2  1.753989   0.819094  3.296673e-73
3          ENO2  1.925520   0.818396  4.772340e-73
4          GYS1  1.210222   0.812043  1.300589e-71
...         ...       ...        ...           ...
1163       GNG4 -0.007283   0.000638  9.526477e-01
1164      BMPR2 -0.001382   0.000020  9.548197e-01
1165       ACTB -0.000628   0.000004  9.787113e-01
1166   ARHGEF28 -0.000407   0.000002  9.845500e-01
1167      PLCE1 -0.000834   0.000002  9.907650e-01

[1168 rows x 4 columns]

In [5]:
Gbm_kidney = pd.merge(df, df2, on="Comparison", how = "outer")
Gbm_kidney = Gbm_kidney.rename(columns={"Slope_x": "Slope_Gbm", "R_squared_x": "R_squared_gbm","P_value_x": "P_value_Gbm" })
Gbm_kidney = Gbm_kidney.rename(columns={"Slope_y": "Slope_kidney", "R_squared_y": "R_squared_kidney","P_value_y": "P_value_kidney" })
#Gbm_kidney.to_csv("GBM_Kidney_EGFR_all.csv")
Gbm_kidney

,Comparison,Slope_Gbm,R_squared_gbm,P_value_Gbm,Slope_kidney,R_squared_kidney,P_value_kidney
0,GRB2,-0.163726,0.411569,5.651892e-14,0.195011,0.319004,9.660917e-18
1,SOX9,0.248300,0.273587,5.382478e-09,0.198859,0.106856,2.405923e-03
2,CDKN2C,0.275173,0.236286,8.399510e-08,0.506703,0.530291,2.460994e-33
3,GAB1,0.142447,0.215491,3.690040e-07,-0.175248,0.186886,3.084590e-10
4,DBI,0.181830,0.213618,4.209130e-07,-0.648547,0.573923,2.362286e-15
...,...,...,...,...,...,...,...
1298,FZD8,NaN,NaN,NaN,0.045895,0.012097,7.954309e-01
1299,ZFP36,NaN,NaN,NaN,0.013893,0.000535,8.277182e-01
1300,GPX2,NaN,NaN,NaN,0.020950,0.000404,8.649464e-01
1301,GSTT2,NaN,NaN,NaN,-0.020739,0.000401,9.391942e-01
1302,ARHGEF28,NaN,NaN,NaN,-0.000407,0.000002,9.845500e-01

# Endometrial

In [6]:
df3 = pd.read_csv("Endo_EGFR.csv")
df3 = df3.drop(['Unnamed: 0'], axis=1)
df3

     Comparison     Slope     R_squared       P_value
0          FZD1  0.859456  4.623879e-01  7.118480e-21
1         LPAR1  1.112053  5.200083e-01  1.572485e-20
2          GJA1  1.068594  4.035266e-01  1.215375e-17
3         ITGA6  0.681367  4.001148e-01  1.829632e-17
4          GNAQ  0.521175  3.856009e-01  1.016882e-16
...         ...       ...           ...           ...
1041     PIK3CD  0.001265  3.383029e-06  9.825443e-01
1042      VPS39 -0.000426  1.700814e-06  9.876226e-01
1043     TXNRD3 -0.000935  1.555421e-06  9.881634e-01
1044      VPS41  0.000217  4.166924e-07  9.938733e-01
1045     UGT1A6 -0.001154  5.776204e-07  9.948012e-01

[1046 rows x 4 columns]

In [7]:
pancan = pd.merge(Gbm_kidney, df3, on="Comparison", how = "outer")
pancan = pancan.rename(columns={"Slope": "Slope_Endo", "R_squared": "R_squared_Endo","P_value": "P_value_Endo" })
pancan

,Comparison,Slope_Gbm,R_squared_gbm,P_value_Gbm,Slope_kidney,R_squared_kidney,P_value_kidney,Slope_Endo,R_squared_Endo,P_value_Endo
0,GRB2,-0.163726,0.411569,5.651892e-14,0.195011,0.319004,9.660917e-18,-0.259424,0.198915,2.115855e-08
1,SOX9,0.248300,0.273587,5.382478e-09,0.198859,0.106856,2.405923e-03,0.146958,0.011617,2.296318e-01
2,CDKN2C,0.275173,0.236286,8.399510e-08,0.506703,0.530291,2.460994e-33,0.044002,0.000971,7.108212e-01
3,GAB1,0.142447,0.215491,3.690040e-07,-0.175248,0.186886,3.084590e-10,0.013304,0.000131,8.917452e-01
4,DBI,0.181830,0.213618,4.209130e-07,-0.648547,0.573923,2.362286e-15,-0.252010,0.106507,6.552258e-05
...,...,...,...,...,...,...,...,...,...,...
1343,LIF,NaN,NaN,NaN,NaN,NaN,NaN,-0.015174,0.000198,9.045230e-01
1344,ELK4,NaN,NaN,NaN,NaN,NaN,NaN,-0.014873,0.000479,9.069917e-01
1345,PKN3,NaN,NaN,NaN,NaN,NaN,NaN,-0.005196,0.000053,9.601432e-01
1346,PLA2G10,NaN,NaN,NaN,NaN,NaN,NaN,-0.008684,0.000055,9.714129e-01
1347,PPP5D1,NaN,NaN,NaN,NaN,NaN,NaN,0.033712,0.000519,9.772266e-01

# Ovarian

In [8]:
df_Ovar = pd.read_csv("Ovar_EGFR.csv")
df_Ovar = df_Ovar.drop(['Unnamed: 0'], axis=1)
df_Ovar

     Comparison     Slope     R_squared       P_value
0         GNG12  0.894236  4.625824e-01  2.767523e-15
1          TNXB  1.768379  4.206725e-01  1.284614e-13
2         GNA11  0.778056  3.639049e-01  1.545209e-11
3         LAMB2  1.267645  3.614795e-01  1.878592e-11
4          CBR3  0.665762  3.453186e-01  6.783385e-11
...         ...       ...           ...           ...
1085       CD48  0.002332  1.713003e-06  9.895313e-01
1086      PDGFC -0.001740  1.464297e-06  9.911248e-01
1087       TCF7  0.001105  4.111950e-07  9.970830e-01
1088      NCOA2  0.000006  7.634313e-11  9.999301e-01
1089      PTPRC  0.000007  2.207042e-11  9.999624e-01

[1090 rows x 4 columns]

In [9]:
pancan = pd.merge(pancan, df_Ovar, on="Comparison", how = "outer")
pancan = pancan.rename(columns={"Slope": "Slope_Ovar", "R_squared": "R_squared_Ovar","P_value": "P_value_Ovar" })
pancan

,Comparison,Slope_Gbm,R_squared_gbm,P_value_Gbm,Slope_kidney,R_squared_kidney,P_value_kidney,Slope_Endo,R_squared_Endo,P_value_Endo,Slope_Ovar,R_squared_Ovar,P_value_Ovar
0,GRB2,-0.163726,0.411569,5.651892e-14,0.195011,0.319004,9.660917e-18,-0.259424,0.198915,2.115855e-08,-0.028630,0.001750,0.674800
1,SOX9,0.248300,0.273587,5.382478e-09,0.198859,0.106856,2.405923e-03,0.146958,0.011617,2.296318e-01,0.127774,0.005857,0.442268
2,CDKN2C,0.275173,0.236286,8.399510e-08,0.506703,0.530291,2.460994e-33,0.044002,0.000971,7.108212e-01,0.748923,0.184052,0.000006
3,GAB1,0.142447,0.215491,3.690040e-07,-0.175248,0.186886,3.084590e-10,0.013304,0.000131,8.917452e-01,0.485464,0.112324,0.000960
4,DBI,0.181830,0.213618,4.209130e-07,-0.648547,0.573923,2.362286e-15,-0.252010,0.106507,6.552258e-05,0.119505,0.011114,0.289214
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1518,CSNK2A3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.042966,0.004713,0.490777
1519,SCNN1A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.196870,0.020744,0.492165
1520,WNT10A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.227446,0.018081,0.512525
1521,CACNA1S,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.865460,0.025319,0.682604
1522,BLK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.008225,0.000028,0.959658

# BRCA

In [10]:
df_Brca = pd.read_csv("Brca_EGFR.csv")
df_Brca = df_Brca.drop(['Unnamed: 0'], axis=1)
df_Brca

     Comparison     Slope     R_squared       P_value
0         PSAT1  1.051931  3.712693e-01  4.973595e-13
1       ANGPTL4  0.741152  3.513292e-01  2.980158e-12
2       PLA2G4A  0.518085  3.389125e-01  8.850043e-12
3          PFKP  0.537796  3.109685e-01  9.562825e-11
4         FOXA1 -0.514515  3.039244e-01  1.717435e-10
...         ...       ...           ...           ...
996        PAK4 -0.000565  9.031676e-07  9.919574e-01
997    HSP90AA1 -0.000284  8.235590e-07  9.923200e-01
998        TNXB  0.000972  6.855229e-07  9.929931e-01
999       RASA4  0.000206  9.491605e-08  9.973927e-01
1000       GNG5 -0.000006  9.574159e-11  9.999172e-01

[1001 rows x 4 columns]

In [11]:
pancan = pd.merge(pancan, df_Brca, on="Comparison", how = "outer")
pancan = pancan.rename(columns={"Slope": "Slope_Brca", "R_squared": "R_squared_Brca","P_value": "P_value_Brca" })
pancan

,Comparison,Slope_Gbm,R_squared_gbm,P_value_Gbm,Slope_kidney,R_squared_kidney,P_value_kidney,Slope_Endo,R_squared_Endo,P_value_Endo,Slope_Ovar,R_squared_Ovar,P_value_Ovar,Slope_Brca,R_squared_Brca,P_value_Brca
0,GRB2,-0.163726,0.411569,5.651892e-14,0.195011,0.319004,9.660917e-18,-0.259424,0.198915,2.115855e-08,-0.028630,0.001750,0.674800,-0.103359,0.031463,0.057899
1,SOX9,0.248300,0.273587,5.382478e-09,0.198859,0.106856,2.405923e-03,0.146958,0.011617,2.296318e-01,0.127774,0.005857,0.442268,0.281249,0.063968,0.006389
2,CDKN2C,0.275173,0.236286,8.399510e-08,0.506703,0.530291,2.460994e-33,0.044002,0.000971,7.108212e-01,0.748923,0.184052,0.000006,0.176449,0.059946,0.008360
3,GAB1,0.142447,0.215491,3.690040e-07,-0.175248,0.186886,3.084590e-10,0.013304,0.000131,8.917452e-01,0.485464,0.112324,0.000960,-0.077163,0.019873,0.132903
4,DBI,0.181830,0.213618,4.209130e-07,-0.648547,0.573923,2.362286e-15,-0.252010,0.106507,6.552258e-05,0.119505,0.011114,0.289214,0.159756,0.037454,0.038234
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1683,MAPK15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.052256,0.002911,0.566876
1684,HLA-DQA2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.075680,0.003984,0.609084
1685,LAMB4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.042367,0.001038,0.771134
1686,ZAK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.012157,0.000402,0.831480
1687,ZAK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.012157,0.000402,0.831480

# Luad

In [12]:
df_Luad = pd.read_csv("Luad_EGFR.csv")
df_Luad = df_Luad.drop(['Unnamed: 0'], axis=1)
df_Luad

     Comparison     Slope     R_squared       P_value
0           MET  0.587682  2.425613e-01  2.050597e-14
1         PRKCB -0.293791  2.013718e-01  5.982751e-12
2         PLCG2 -0.268640  1.801372e-01  1.005408e-10
3        PPP3CB -0.172871  1.678932e-01  4.966798e-10
4          STK3  0.239426  1.663551e-01  6.061641e-10
...         ...       ...           ...           ...
1046        GPI  0.000561  9.207060e-07  9.888926e-01
1047     NFKBIA -0.000559  7.793014e-07  9.897810e-01
1048      ANXA1  0.000610  4.909777e-07  9.918887e-01
1049       ARNT  0.000188  2.560448e-07  9.941424e-01
1050       NOS3 -0.000215  5.150873e-08  9.973727e-01

[1051 rows x 4 columns]

In [13]:
pancan = pd.merge(pancan, df_Luad, on="Comparison", how = "outer")
pancan = pancan.rename(columns={"Slope": "Slope_Luad", "R_squared": "R_squared_Luad","P_value": "P_value_Luad" })
pancan

,Comparison,Slope_Gbm,R_squared_gbm,P_value_Gbm,Slope_kidney,R_squared_kidney,P_value_kidney,Slope_Endo,R_squared_Endo,P_value_Endo,Slope_Ovar,R_squared_Ovar,P_value_Ovar,Slope_Brca,R_squared_Brca,P_value_Brca,Slope_Luad,R_squared_Luad,P_value_Luad
0,GRB2,-0.163726,0.411569,5.651892e-14,0.195011,0.319004,9.660917e-18,-0.259424,0.198915,2.115855e-08,-0.028630,0.001750,0.674800,-0.103359,0.031463,0.057899,-0.131561,0.092538,0.000006
1,SOX9,0.248300,0.273587,5.382478e-09,0.198859,0.106856,2.405923e-03,0.146958,0.011617,2.296318e-01,0.127774,0.005857,0.442268,0.281249,0.063968,0.006389,NaN,NaN,NaN
2,CDKN2C,0.275173,0.236286,8.399510e-08,0.506703,0.530291,2.460994e-33,0.044002,0.000971,7.108212e-01,0.748923,0.184052,0.000006,0.176449,0.059946,0.008360,-0.210660,0.075321,0.000049
3,GAB1,0.142447,0.215491,3.690040e-07,-0.175248,0.186886,3.084590e-10,0.013304,0.000131,8.917452e-01,0.485464,0.112324,0.000960,-0.077163,0.019873,0.132903,-0.126900,0.017451,0.054220
4,DBI,0.181830,0.213618,4.209130e-07,-0.648547,0.573923,2.362286e-15,-0.252010,0.106507,6.552258e-05,0.119505,0.011114,0.289214,0.159756,0.037454,0.038234,-0.169133,0.066253,0.000145
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2036,FLT3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.081122,0.008828,0.171881
2037,HLA-DQB2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.150322,0.008210,0.252989
2038,WNT7B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.098084,0.009587,0.347797
2039,SLC6A4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.111172,0.002906,0.433847
2040,PIK3R5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.096310,0.000505,0.782787

# HNSCC

In [14]:
df_hnscc = pd.read_csv("Hnscc_EGFR.csv")
df_hnscc = df_hnscc.drop(['Unnamed: 0'], axis=1)
df_hnscc

    Comparison     Slope     R_squared       P_value
0     MAPK8IP3 -0.013008  1.000000e+00  0.000000e+00
1         PSPH  0.177054  3.470895e-01  1.311172e-19
2         PFKP  0.121046  2.382679e-01  3.441673e-13
3         JAG1  0.046958  2.339778e-01  4.217477e-09
4         GJA1  0.030686  1.537993e-01  7.989725e-08
..         ...       ...           ...           ...
851      ITGB4 -0.000552  2.617308e-07  9.943072e-01
852      ICAM1 -0.000087  4.381066e-08  9.976709e-01
853      PTPRA  0.000282  4.142399e-08  9.979046e-01
854       CDK1  0.000013  1.225882e-08  9.988297e-01
855      FABP1       NaN  0.000000e+00           NaN

[856 rows x 4 columns]

In [15]:
pancan = pd.merge(pancan, df_hnscc, on="Comparison", how = "outer")
pancan = pancan.rename(columns={"Slope": "Slope_hnscc", "R_squared": "R_squared_hnscc","P_value": "P_value_hnscc" })
pancan

,Comparison,Slope_Gbm,R_squared_gbm,P_value_Gbm,Slope_kidney,R_squared_kidney,P_value_kidney,Slope_Endo,R_squared_Endo,P_value_Endo,...,P_value_Ovar,Slope_Brca,R_squared_Brca,P_value_Brca,Slope_Luad,R_squared_Luad,P_value_Luad,Slope_hnscc,R_squared_hnscc,P_value_hnscc
0,GRB2,-0.163726,0.411569,5.651892e-14,0.195011,0.319004,9.660917e-18,-0.259424,0.198915,2.115855e-08,...,0.674800,-0.103359,0.031463,0.057899,-0.131561,0.092538,0.000006,-0.045965,0.040168,0.004745
1,SOX9,0.248300,0.273587,5.382478e-09,0.198859,0.106856,2.405923e-03,0.146958,0.011617,2.296318e-01,...,0.442268,0.281249,0.063968,0.006389,NaN,NaN,NaN,NaN,NaN,NaN
2,CDKN2C,0.275173,0.236286,8.399510e-08,0.506703,0.530291,2.460994e-33,0.044002,0.000971,7.108212e-01,...,0.000006,0.176449,0.059946,0.008360,-0.210660,0.075321,0.000049,NaN,NaN,NaN
3,GAB1,0.142447,0.215491,3.690040e-07,-0.175248,0.186886,3.084590e-10,0.013304,0.000131,8.917452e-01,...,0.000960,-0.077163,0.019873,0.132903,-0.126900,0.017451,0.054220,-0.003759,0.043428,0.016912
4,DBI,0.181830,0.213618,4.209130e-07,-0.648547,0.573923,2.362286e-15,-0.252010,0.106507,6.552258e-05,...,0.289214,0.159756,0.037454,0.038234,-0.169133,0.066253,0.000145,-0.170365,0.035367,0.008135
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2049,CLEC4G,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.007047,0.046876,0.522539
2050,PLA2G4D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.060677,0.011633,0.537418
2051,WNT3A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.005338,0.378260,0.578289
2052,BMP2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.002719,0.263358,0.656932
2053,IL17B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.094212,0.003484,0.717516

In [17]:
pancan.to_csv("pancan_EGFR.csv")