In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats
import re
import sys 
import statsmodels.stats.multitest
#sys.path.append('C:\\Users\\brittany\\henderson\\GitHub\\GBM_for_CPTAC\\')
#import cis_functions as f
#sys.path.append('C:\\Users\\Lindsey\\Documents\\GitHub\\WhenMutationsDontMatter\\')
#import plot_utils as p


import cptac
import cptac.utils as u

In [43]:
df = pd.read_csv('pancan_EGFR.csv')
df = df.drop(['Unnamed: 0'], axis=1)
filtered_data = df[df["Comparison"]== "ARG1"]
filtered_data

,Comparison,Slope_Gbm,R_squared_gbm,P_value_Gbm,Slope_kidney,R_squared_kidney,P_value_kidney,Slope_Endo,R_squared_Endo,P_value_Endo,...,P_value_Ovar,Slope_Brca,R_squared_Brca,P_value_Brca,Slope_Luad,R_squared_Luad,P_value_Luad,Slope_hnscc,R_squared_hnscc,P_value_hnscc
1740,ARG1,-0.006077,0.000103,0.91659,0.754793,0.295593,4.426750e-15,-0.125737,0.007966,0.287412,...,0.000002,0.367109,0.080817,0.002076,-0.388205,0.062622,0.000225,-3.567485,0.004205,0.375357

In [36]:
df_slope = df.loc[:,["Comparison","Slope_Gbm","Slope_kidney","Slope_Endo","Slope_Ovar","Slope_Brca","Slope_Luad","Slope_hnscc"]]

In [46]:
df_slope["SD"] = (df_slope.loc[:,["Slope_Gbm","Slope_kidney","Slope_Endo","Slope_Ovar","Slope_Brca","Slope_Luad","Slope_hnscc"]].std(axis = 1))
df_slope = df_slope.dropna(thresh = 5)

In [47]:
df_slope.nlargest(10, 'SD')

,Comparison,Slope_Gbm,Slope_kidney,Slope_Endo,Slope_Ovar,Slope_Brca,Slope_Luad,Slope_hnscc,SD
1142,MYL1,-0.070427,-0.296202,NaN,0.344465,NaN,-0.180677,-8.715718,3.882641
657,ACVR1,-0.044394,-0.120272,0.385674,0.069127,0.276709,0.199224,-8.825737,3.388709
1280,VIM,0.070424,0.946759,0.332321,0.595027,0.287442,-0.132727,-7.306996,2.915014
1831,ITGB6,NaN,-0.819923,0.577964,0.438791,0.542116,-0.050240,-5.776941,2.471975
72,MET,-0.157167,0.927873,0.212156,0.167618,0.736808,0.587682,-4.582195,1.923936
1349,SERPINA1,-0.049350,0.209853,0.221388,1.330491,0.158214,-0.330752,-4.205985,1.764226
611,GFAP,0.139648,NaN,0.246446,0.699214,0.439710,NaN,-3.218248,1.623746
1475,CCL20,-0.046228,0.553596,-0.148086,3.629718,NaN,-0.106711,NaN,1.620366
1740,ARG1,-0.006077,0.754793,-0.125737,0.963529,0.367109,-0.388205,-3.567485,1.525000
1487,ITGAX,-0.019922,1.448414,0.172074,-0.210494,0.150228,-0.074419,-2.506430,1.178123