In [11]:
import pandas as pd, numpy as np, seaborn as sns, matplotlib.pyplot as plt, sys
sys.path.insert(0, "/Users/lili/dropbox_lili/common_functions/outlier_analysis/")
import blackSheepCPTACmodule as ol

In [12]:
import importlib
importlib.reload(ol)

In [14]:
test_table = np.array([[0, np.nan, 1, 2, 10],
                      [1, 2, 1, 40, 3],
                      [0, 2, 50, np.nan, 1],
                      [0, -2, -3, 45, 90],
                      [-1, -2, -3, 10, 5]])
cols = ['sampA', 'sampB', 'sampC', 'sampD', 'sampE']
index = ['gene1-psite1', 'gene1-psite2', 'gene2-psite1', 'gene3-psite1', 'gene4-psite1']
test_table = pd.DataFrame(test_table, columns=cols, index=index).transpose()

In [15]:
test_table

       gene1-psite1  gene1-psite2  gene2-psite1  gene3-psite1  gene4-psite1
sampA           0.0           1.0           0.0           0.0          -1.0
sampB           NaN           2.0           2.0          -2.0          -2.0
sampC           1.0           1.0          50.0          -3.0          -3.0
sampD           2.0          40.0           NaN          45.0          10.0
sampE          10.0           3.0           1.0          90.0           5.0

# Making the outliers table
##### Note--frac_table is useful for visualization but is not used for statistics.

In [16]:
help(ol.make_outliers_table)

Help on function make_outliers_table in module blackSheepCPTACmodule:

make_outliers_table(df, iqrs=1.5, up_or_down='up', aggregate=True, frac_table=False)

In [17]:
# With all of the default parameters
outliers = ol.make_outliers_table(test_table,iqrs=1.5, up_or_down='up', aggregate=True, frac_table=False)
outliers

agg_col            gene1  gene2  gene3  gene4
sampA_notOutliers    2.0    1.0    1.0    1.0
sampB_notOutliers    1.0    1.0    1.0    1.0
sampC_notOutliers    2.0    0.0    1.0    1.0
sampD_notOutliers    1.0    0.0    1.0    0.0
sampE_notOutliers    1.0    1.0    0.0    1.0
sampA_outliers       0.0    0.0    0.0    0.0
sampB_outliers       0.0    0.0    0.0    0.0
sampC_outliers       0.0    1.0    0.0    0.0
sampD_outliers       1.0    0.0    0.0    1.0
sampE_outliers       1.0    0.0    1.0    0.0

In [21]:
# Aggregation off, and a fraction outliers table for visualization
outliers, frac_table = ol.make_outliers_table(test_table,iqrs=1.5, up_or_down='up', aggregate=False, frac_table=True)
outliers

,gene1-psite1,gene1-psite2,gene2-psite1,gene3-psite1,gene4-psite1
sampA_outliers,0.0,0.0,0.0,0.0,0.0
sampB_outliers,NaN,0.0,0.0,0.0,0.0
sampC_outliers,0.0,0.0,1.0,0.0,0.0
sampD_outliers,0.0,1.0,NaN,0.0,1.0
sampE_outliers,1.0,0.0,0.0,1.0,0.0
sampA_notOutliers,1.0,1.0,1.0,1.0,1.0
sampB_notOutliers,NaN,1.0,1.0,1.0,1.0
sampC_notOutliers,1.0,1.0,0.0,1.0,1.0
sampD_notOutliers,1.0,0.0,NaN,1.0,0.0
sampE_notOutliers,0.0,1.0,1.0,0.0,1.0

In [12]:
frac_table

       gene1-psite1  gene1-psite2  gene2-psite1  gene3-psite1  gene4-psite1
sampA           0.0           0.0           0.0           0.0           0.0
sampB           NaN           0.0           0.0           0.0           0.0
sampC           0.0           0.0           1.0           0.0           0.0
sampD           0.0           1.0           NaN           0.0           1.0
sampE           1.0           0.0           0.0           1.0           0.0

In [28]:
# Fraction table with aggreagation
frac_table = ol.make_outliers_table(test_table,iqrs=1.5, up_or_down='up', aggregate=True, frac_table=True)[1]
frac_table

agg_col  gene1  gene2  gene3  gene4
sampA      0.0    0.0    0.0    0.0
sampB      0.0    0.0    0.0    0.0
sampC      0.0    1.0    0.0    0.0
sampD      0.5    NaN    0.0    1.0
sampE      0.5    0.0    1.0    0.0

# Comparing different groups using outliers

In [33]:
labels = np.array([[0, 0, 0, 1, 1], [0, 1, 0, 1, 0]]).transpose()
annotations = pd.DataFrame(labels, index=cols, columns=['comparison1', 'comparison2'])
annotations

       comparison1  comparison2
sampA            0            0
sampB            0            1
sampC            0            0
sampD            1            1
sampE            1            0

In [39]:
# Without aggregating psites
outliers = ol.make_outliers_table(test_table,iqrs=1.5, up_or_down='up', aggregate=False, frac_table=False)
results = ol.compare_groups_outliers(outliers, annotations)
results

Testing 1 rows for enrichment in comparison1 0 samples
Testing 4 rows for enrichment in comparison1 1 samples
Testing 3 rows for enrichment in comparison2 0 samples
Testing 2 rows for enrichment in comparison2 1 samples

,comparison1_0_enrichment_FDR,comparison1_1_enrichment_FDR,comparison2_0_enrichment_FDR,comparison2_1_enrichment_FDR
gene1-psite1,NaN,1.000000,1.0,NaN
gene1-psite2,NaN,0.533333,NaN,0.4
gene2-psite1,1.0,NaN,1.0,NaN
gene3-psite1,NaN,0.533333,1.0,NaN
gene4-psite1,NaN,0.533333,NaN,0.4

In [40]:
# With aggregating psites
outliers = ol.make_outliers_table(test_table,iqrs=1.5, up_or_down='up', aggregate=True, frac_table=False)
results = ol.compare_groups_outliers(outliers, annotations)
results

Testing 1 rows for enrichment in comparison1 0 samples
Testing 3 rows for enrichment in comparison1 1 samples
Testing 2 rows for enrichment in comparison2 0 samples
Testing 2 rows for enrichment in comparison2 1 samples

,comparison1_0_enrichment_FDR,comparison1_1_enrichment_FDR,comparison2_0_enrichment_FDR,comparison2_1_enrichment_FDR
gene1,NaN,0.4,NaN,1.0
gene2,1.0,NaN,1.0,NaN
gene3,NaN,0.4,1.0,NaN
gene4,NaN,0.4,NaN,0.8

In [2]:
import CPTAC.Endometrial as en

Welcome to the CPTAC data service package. Available datasets may be
viewed using CPTAC.list_data(). In order to access a specific data
set, import a CPTAC subfolder using either 'import CPTAC.Dataset' or
'from CPTAC import Dataset'.
******
Version: 0.3.1
******
Loading Dictionary...
Loading CPTAC Endometrial data:
Loading acetylproteomics data...
Loading clinical data...
Loading CNA data...
Loading definitions data...
Loading miRNA data...
Loading phosphoproteomics_gene data...
Loading phosphoproteomics_site data...
Loading proteomics data...
Loading somatic data...
Loading somatic data...
Loading transcriptomics_circular data...
Loading transcriptomics_linear data...

 ******PLEASE READ******
WARNING: This data is under a publication embargo until July 1, 2019.
CPTAC is a community resource project and data are made available
rapidly after generation for community research use. The embargo
allows exploring and utilizing the data, but the data may not be in a
publication until July 1, 2019. Please see
https://proteomics.cancer.gov/data-portal/about/data-use-agreement or
enter embargo() to open the webpage for more details.

In [3]:
transcriptomics = en.get_transcriptomics()

In [4]:
small_transcriptomics = transcriptomics.iloc[:, 0:10]

In [5]:
small_transcriptomics

idx,A1BG,A1BG-AS1,A1CF,A2M,A2M-AS1,A2ML1,A2MP1,A3GALT2,A4GALT,A4GNT
Sample_ID,,,,,,,,,,
S001,4.02,2.16,3.27,13.39,5.88,6.79,1.55,0.97,10.34,1.96
S002,4.81,2.21,4.86,13.24,5.93,6.33,0.93,0.00,10.83,0.00
S003,6.24,6.43,3.68,14.32,6.53,9.42,2.79,0.00,10.98,2.13
S005,5.31,4.87,5.59,13.77,6.35,4.22,2.97,0.00,8.68,1.98
S006,9.84,8.83,7.00,13.12,6.49,6.83,1.80,0.00,11.42,3.28
S007,5.03,5.59,4.82,14.13,7.65,7.75,1.59,1.01,9.61,1.59
S008,3.17,3.56,3.98,13.49,6.48,5.88,2.23,1.16,9.71,1.16
S009,6.03,5.46,7.21,13.67,6.95,6.69,2.93,0.00,8.78,1.53
S010,6.02,5.90,7.73,14.30,7.76,8.47,3.47,1.18,9.98,2.26
S011,5.71,5.43,4.20,14.97,6.87,9.96,2.83,0.00,10.22,3.20
S012,5.17,4.89,4.37,13.40,5.69,8.69,1.98,2.79,11.42,0.00
S014,5.38,4.83,2.15,14.13,5.96,11.45,1.44,0.00,10.20,0.00
S016,5.86,6.51,6.17,13.15,7.21,3.65,1.15,0.00,8.37,0.00
S017,3.27,3.60,5.98,12.28,6.23,6.97,3.03,0.00,10.04,2.02
S018,4.65,4.63,4.84,13.42,7.33,10.75,0.00,0.00,10.05,0.00
S019,4.33,4.08,3.94,13.06,5.71,13.60,1.82,0.00,10.04,0.00
S020,4.58,5.16,2.85,15.05,6.74,8.90,3.02,0.92,10.71,2.18
S021,4.60,4.64,5.74,12.69,6.85,9.56,1.54,1.54,9.60,0.97
S022,4.90,4.49,6.51,14.13,5.82,5.44,0.00,1.28,9.49,0.78
S023,4.03,4.11,4.20,13.07,6.14,4.46,1.66,0.78,7.10,0.78
S024,4.62,3.83,3.95,14.12,6.35,11.77,1.43,0.89,10.29,1.83
S025,5.46,4.96,4.75,13.98,7.25,3.94,1.95,1.54,10.04,0.00
S026,5.73,5.03,4.43,14.70,6.87,8.07,2.48,0.00,9.90,3.54
S027,4.13,2.36,3.56,13.13,5.24,4.68,0.00,1.74,10.74,0.00
S028,6.08,5.48,4.58,15.56,7.35,5.92,2.14,2.14,10.17,0.89
S029,5.24,4.88,3.82,14.48,6.87,5.87,2.92,1.53,10.02,2.25
S030,7.36,6.61,3.98,14.15,6.90,8.97,2.87,1.04,10.23,0.00
S031,5.73,4.58,4.38,13.36,6.86,5.60,0.00,0.93,10.06,0.00
S032,5.31,4.91,4.10,14.65,5.81,5.02,1.39,1.78,10.22,1.78
S033,4.00,5.96,4.47,14.71,7.52,11.18,3.43,0.00,10.31,1.40
...,...,...,...,...,...,...,...,...,...,...
S087,5.41,5.64,4.03,13.50,6.55,7.49,3.02,2.18,11.24,1.75
S088,6.65,7.28,3.84,13.37,6.28,5.12,1.88,0.92,10.17,1.48
S090,7.44,6.98,5.10,14.90,8.40,5.22,3.13,0.00,9.63,0.00
S091,3.79,4.46,2.08,15.16,6.52,9.16,2.33,0.00,8.98,0.00
S092,6.94,6.75,3.95,13.08,6.55,6.25,1.38,0.85,10.28,3.41
S093,4.95,5.48,1.55,14.86,7.25,9.54,2.96,0.98,10.81,1.96
S094,5.34,5.77,3.75,13.84,8.44,7.95,4.25,0.00,9.17,2.13
S095,5.22,5.50,6.00,14.73,7.16,7.26,1.58,0.00,8.77,1.87
S096,5.63,6.89,3.55,13.96,7.40,11.41,2.40,0.00,7.80,1.65
S097,7.63,7.54,4.98,13.49,7.01,6.43,0.95,1.51,8.99,1.92
S098,4.85,3.44,4.37,12.88,6.38,8.45,2.38,0.00,9.64,0.00
S099,4.84,4.95,2.77,13.37,6.43,5.90,1.96,1.29,9.84,0.00
S100,4.80,5.02,2.87,13.40,7.15,5.12,0.93,0.00,10.64,0.00
S101,5.95,5.92,5.53,14.23,7.64,11.96,1.73,0.00,8.05,2.16
S102,5.25,5.97,5.04,13.75,6.02,2.06,1.04,0.00,9.87,1.04
S103,6.79,6.72,7.97,14.96,7.24,7.50,2.44,0.00,8.83,3.45
S105,6.42,6.35,2.73,16.07,9.19,4.96,3.44,0.00,8.96,3.01
S106,7.04,7.15,3.96,16.09,8.50,4.43,3.47,0.00,9.24,4.06
S107,6.82,7.27,3.70,16.28,8.04,4.82,3.93,1.67,9.03,2.92
S108,7.24,7.11,3.67,15.41,8.64,4.65,4.61,0.00,9.09,2.17
S111,5.92,6.48,3.66,15.38,7.92,7.00,3.52,1.73,9.37,1.73
S119,6.57,6.50,4.62,15.79,7.92,5.44,3.68,0.99,9.42,3.98
S120,6.45,7.05,3.99,15.61,8.69,4.60,4.84,0.00,10.05,2.66
S121,7.46,6.92,2.94,16.18,8.47,5.05,4.30,1.88,9.12,3.37
S122,6.56,6.52,4.16,15.62,8.22,4.06,3.85,0.00,9.54,2.46
S124,7.05,7.26,3.71,15.84,8.22,5.70,3.57,0.00,9.03,2.21
S125,6.58,6.92,2.29,16.02,8.88,5.86,4.44,1.84,9.47,3.66
S127,7.36,7.55,2.99,15.17,8.68,5.64,3.65,2.16,8.59,1.73
S128,6.80,6.43,2.72,16.02,7.95,4.51,3.28,1.29,9.37,1.29
S129,7.61,7.53,2.40,16.07,8.62,6.95,3.09,0.00,9.49,1.05

In [19]:
outliers = ol.make_outliers_table(small_transcriptomics,iqrs=1.5, up_or_down='up', aggregate=True, frac_table=False)
outliers

agg_col           A1BG  A1CF  A2M  A2ML1  A2MP1  A3GALT2  A4GALT  A4GNT
S001_notOutliers     2     1    2      1      1        1       1      1
S002_notOutliers     2     1    2      1      1        1       1      1
S003_notOutliers     2     1    2      1      1        1       1      1
S005_notOutliers     2     1    2      1      1        1       1      1
S006_notOutliers     0     0    2      1      1        1       1      1
S007_notOutliers     2     1    2      1      1        1       1      1
S008_notOutliers     2     1    2      1      1        1       1      1
S009_notOutliers     2     0    2      1      1        1       1      1
S010_notOutliers     2     0    2      1      1        1       1      1
S011_notOutliers     2     1    2      1      1        1       1      1
S012_notOutliers     2     1    2      1      1        0       1      1
S014_notOutliers     2     1    2      1      1        1       1      1
S016_notOutliers     2     1    2      1      1        1       1      1
S017_notOutliers     2     1    2      1      1        1       1      1
S018_notOutliers     2     1    2      1      1        1       1      1
S019_notOutliers     2     1    2      0      1        1       1      1
S020_notOutliers     2     1    2      1      1        1       1      1
S021_notOutliers     2     1    2      1      1        1       1      1
S022_notOutliers     2     0    2      1      1        1       1      1
S023_notOutliers     2     1    2      1      1        1       1      1
S024_notOutliers     2     1    2      0      1        1       1      1
S025_notOutliers     2     1    2      1      1        1       1      1
S026_notOutliers     2     1    2      1      1        1       1      1
S027_notOutliers     2     1    2      1      1        1       1      1
S028_notOutliers     2     1    2      1      1        0       1      1
S029_notOutliers     2     1    2      1      1        1       1      1
S030_notOutliers     2     1    2      1      1        1       1      1
S031_notOutliers     2     1    2      1      1        1       1      1
S032_notOutliers     2     1    2      1      1        1       1      1
S033_notOutliers     2     1    2      1      1        1       1      1
...                ...   ...  ...    ...    ...      ...     ...    ...
S087_outliers        0     0    0      0      0        1       0      0
S088_outliers        0     0    0      0      0        0       0      0
S090_outliers        0     0    0      0      0        0       0      0
S091_outliers        0     0    0      0      0        0       0      0
S092_outliers        0     0    0      0      0        0       0      0
S093_outliers        0     0    0      0      0        0       0      0
S094_outliers        0     0    0      0      0        0       0      0
S095_outliers        0     0    0      0      0        0       0      0
S096_outliers        0     0    0      0      0        0       0      0
S097_outliers        0     0    0      0      0        0       0      0
S098_outliers        0     0    0      0      0        0       0      0
S099_outliers        0     0    0      0      0        0       0      0
S100_outliers        0     0    0      0      0        0       0      0
S101_outliers        0     0    0      1      0        0       0      0
S102_outliers        0     0    0      0      0        0       0      0
S103_outliers        0     1    0      0      0        0       0      0
S105_outliers        0     0    2      0      0        0       0      0
S106_outliers        0     0    1      0      0        0       0      1
S107_outliers        0     0    1      0      0        0       0      0
S108_outliers        0     0    1      0      1        0       0      0
S111_outliers        0     0    0      0      0        0       0      0
S119_outliers        0     0    0      0      0        0       0      1
S120_outliers        0     0    1      0      1        0       0      0
S121_outliers        0     0    1      0      0        0       0      0
S122_outliers        0     0    0      0      0        0       0      0
S124_outliers        0     0    0      0      0        0       0      0
S125_outliers        0     0    2      0      0        0       0      0
S127_outliers        0     0    1      0      0        1       0      0
S128_outliers        0     0    1      0      0        0       0      0
S129_outliers        0     0    2      0      0        0       0      0

[218 rows x 8 columns]