# Examine trans effect of TP53 Hotspot mutation in Endometrial Cancer

### Specifically examine Protein Abundance and Phosphorylation of PLK1

#### Library Imports

In [2]:
import pandas as pd
import numpy as np
import scipy.stats

import cptac
import cptac.utils as ut

import seaborn as sns
import matplotlib.pyplot as plt

#Use Endometrial cancer object
co = cptac.Endometrial()

In [4]:
gene = 'ARID1A'
omics = 'proteomics'

In [17]:
interacting_proteins = ut.get_interacting_proteins_bioplex(gene)
interacting_proteins

['BCL7A', 'BCL7C', 'SMARCD1', 'DPF2', 'DPF3', 'SMARCE1', 'SS18', 'SMARCC2']

In [18]:
proteomics_df = co.join_omics_to_mutations(mutations_genes=gene,omics_df_name=omics, omics_genes=interacting_proteins)
proteomics_df.head()

Warning: In joining the somatic_mutation table, no mutations were found for the following samples, so they were filled with Wildtype_Tumor or Wildtype_Normal: 101 samples for the ARID1A gene (/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py, line 1)

Name,BCL7A_proteomics,BCL7C_proteomics,SMARCD1_proteomics,DPF2_proteomics,DPF3_proteomics,SMARCE1_proteomics,SS18_proteomics,SMARCC2_proteomics,ARID1A_Mutation,ARID1A_Location,ARID1A_Mutation_Status,Sample_Status
Sample_ID,,,,,,,,,,,,
S001,0.4100,-0.9180,-0.328,-0.548,NaN,-0.3950,-0.498,-0.451,[Missense_Mutation],[p.T2121P],Single_mutation,Tumor
S002,0.8880,-0.9410,-0.418,-0.919,NaN,-0.5560,-0.162,-0.627,"[Nonsense_Mutation, Frame_Shift_Del]","[p.Q403*, p.D1850Tfs*33]",Multiple_mutation,Tumor
S003,0.0927,-0.3880,-0.648,-0.555,NaN,-0.5400,-0.448,-0.537,[Wildtype_Tumor],[No_mutation],Wildtype_Tumor,Tumor
S005,0.6880,-0.0328,0.186,0.372,NaN,0.0968,0.203,-0.102,[Wildtype_Tumor],[No_mutation],Wildtype_Tumor,Tumor
S006,0.3460,-1.4000,-0.599,-0.642,NaN,0.0897,0.298,-0.432,[Wildtype_Tumor],[No_mutation],Wildtype_Tumor,Tumor

In [19]:
proteomics_df = proteomics_df.loc[proteomics_df['Sample_Status'] == 'Tumor']

In [20]:
for ind, row in proteomics_df.iterrows():
    if row[gene+'_Mutation_Status'] == 'Wildtype_Tumor':
        proteomics_df.loc[ind, gene+'_Binary'] = 'Wildtype'
    else:
        proteomics_df.loc[ind, gene+'_Binary'] = 'Mutated'
        
proteomics_df = proteomics_df.drop(['ARID1A_Mutation','ARID1A_Location','ARID1A_Mutation_Status', 'Sample_Status'], axis = 1)
proteomics_df

Name,BCL7A_proteomics,BCL7C_proteomics,SMARCD1_proteomics,DPF2_proteomics,DPF3_proteomics,SMARCE1_proteomics,SS18_proteomics,SMARCC2_proteomics,ARID1A_Binary
Sample_ID,,,,,,,,,
S001,0.41000,-0.9180,-0.32800,-0.5480,NaN,-0.395000,-0.49800,-0.45100,Mutated
S002,0.88800,-0.9410,-0.41800,-0.9190,NaN,-0.556000,-0.16200,-0.62700,Mutated
S003,0.09270,-0.3880,-0.64800,-0.5550,NaN,-0.540000,-0.44800,-0.53700,Wildtype
S005,0.68800,-0.0328,0.18600,0.3720,NaN,0.096800,0.20300,-0.10200,Wildtype
S006,0.34600,-1.4000,-0.59900,-0.6420,NaN,0.089700,0.29800,-0.43200,Wildtype
S007,-0.92800,-0.0891,-0.12200,-0.0257,NaN,-0.085900,0.37900,-0.42800,Wildtype
S008,0.27300,-0.1930,0.23700,0.1870,NaN,0.208000,0.05150,0.00000,Mutated
S009,0.94700,0.2780,1.17000,0.7090,NaN,0.566000,0.62400,0.20700,Wildtype
S010,-0.64000,0.0509,-0.02090,-0.0928,NaN,0.101000,-0.00796,0.22500,Wildtype
S011,0.11300,-0.3520,-0.02280,-0.0505,NaN,-0.124000,-0.48700,-0.06530,Wildtype
S012,-0.06450,-1.0800,-0.42800,-0.8230,NaN,-0.757000,-0.20300,-0.88300,Mutated
S014,0.09410,-0.7590,-0.85100,-0.9110,NaN,-0.314000,-0.41400,-0.74700,Mutated
S016,0.79100,0.6130,0.43800,0.6280,NaN,1.110000,0.96600,1.04000,Wildtype
S017,-0.02360,0.0604,-0.09310,0.1290,NaN,-0.005880,-0.03950,-0.09800,Wildtype
S018,0.39400,-0.1640,0.20000,-0.1420,NaN,0.201000,-0.04010,0.38800,Mutated
S019,0.22300,-0.3530,-0.38400,-0.3160,NaN,-0.085000,-0.45500,-0.29200,Mutated
S020,-0.39500,-0.3330,-0.27200,-0.3230,NaN,-0.123000,-0.35100,-0.15700,Wildtype
S021,0.06890,0.1330,-0.09590,0.0940,NaN,-0.087800,0.10800,0.13500,Wildtype
S022,-0.36600,-0.1620,-0.03760,-0.1470,NaN,-0.070800,-0.02960,-0.01760,Mutated
S023,0.78000,-0.3150,-0.22000,0.1360,NaN,0.227000,0.16700,0.14300,Mutated
S024,0.42900,-0.6110,-0.19000,-0.5350,NaN,-0.508000,-0.22200,-0.45700,Mutated
S025,0.80600,-0.4020,0.37300,0.0892,NaN,0.004000,0.11500,-0.04630,Wildtype
S026,-0.03500,-0.2890,0.06040,-0.0395,NaN,-0.055400,-0.12600,0.06310,Mutated
S027,0.06080,-0.3250,-0.23900,-0.4970,NaN,-0.181000,-0.64900,-0.18300,Mutated
S028,-0.31400,0.0945,-0.13900,-0.1380,NaN,-0.284000,-0.03190,-0.00255,Wildtype
S029,-0.59300,0.2840,0.04920,-0.4550,NaN,-0.153000,-0.27300,-0.37900,Wildtype
S030,-0.21500,-0.5350,-0.35500,-1.0400,NaN,-0.442000,-0.58200,-0.56500,Mutated
S031,-0.64800,0.2410,0.30400,0.2710,NaN,0.486000,0.03990,0.62100,Wildtype
S032,0.07560,-0.2010,-0.16400,-0.2690,NaN,-0.063800,-0.16900,-0.14500,Wildtype
S033,0.05700,-0.3640,-0.17200,0.1770,NaN,0.191000,0.21500,0.31200,Wildtype
...,...,...,...,...,...,...,...,...,...
S073,-0.23800,2.0000,-0.24400,-1.1300,NaN,-0.957000,-0.40300,-0.89300,Mutated
S074,0.19200,-0.2280,0.31300,0.2300,NaN,0.110000,-0.02840,0.08960,Wildtype
S075,0.03690,-0.4720,-0.00566,-0.0373,NaN,-0.695000,-0.16500,-0.36900,Wildtype
S076,-0.03360,-0.0521,-0.18000,0.0170,NaN,0.198000,0.01120,0.48900,Wildtype
S077,0.01550,-0.4470,-0.41200,-0.7790,NaN,-0.107000,-0.09510,-0.33600,Mutated
S078,0.05680,-0.5890,-0.24600,-0.4830,NaN,-0.166000,0.15700,0.06540,Mutated
S079,0.17800,-0.2450,-0.77300,-0.7230,NaN,-0.056200,-1.13000,-0.29800,Mutated
S080,0.08370,-0.4640,-0.26800,-0.4550,NaN,-0.013000,-0.29000,-0.43900,Mutated
S081,-0.11800,-0.2060,0.28800,0.0454,NaN,-0.021000,0.28000,-0.09950,Wildtype
S082,-0.46000,0.2600,-0.33800,-0.2990,NaN,0.000694,-0.35000,-0.39500,Wildtype
S083,-0.76700,-0.3610,-0.28700,-0.3420,NaN,-0.289000,-0.02690,-0.73100,Mutated
S084,-0.10200,-0.4760,-0.06800,-0.0735,NaN,0.045600,0.16900,-0.00328,Mutated
S085,0.23900,-0.0991,-0.21200,-0.0903,NaN,0.006490,0.09200,-0.10100,Mutated
S086,0.76100,-0.5580,0.17500,0.1000,NaN,0.125000,0.12400,0.21100,Wildtype
S087,0.79500,-1.0000,-0.46800,-0.6590,NaN,-0.241000,-0.07740,-0.38900,Mutated
S088,0.52400,-0.7110,-0.02140,-0.2610,NaN,-0.510000,0.04400,-0.58900,Wildtype
S090,0.02580,0.1160,0.19300,0.1040,NaN,-0.007350,-0.04760,0.19000,Mutated
S091,0.30100,-0.5810,-0.49400,-0.4510,NaN,-0.268000,-0.38600,-0.46900,Mutated
S092,0.28900,-0.2970,-0.92000,-0.9260,NaN,-0.208000,-0.63100,-0.75500,Mutated
S093,-0.00347,-0.3100,-0.19200,-0.2290,NaN,-0.133000,-0.01670,-0.04730,Mutated
S094,-0.47500,-0.5510,-0.00906,-0.4780,NaN,-0.484000,-0.29200,-0.48400,Mutated
S095,-0.05360,-0.1970,-0.24200,-0.0869,NaN,-0.082400,-0.36900,0.00550,Wildtype
S096,1.05000,0.1610,1.49000,0.1810,NaN,0.403000,0.17900,-0.06850,Wildtype
S097,0.10900,0.4110,0.56200,0.0169,NaN,0.384000,0.16800,0.49500,Wildtype
S098,0.57600,-0.8110,0.07130,-0.4960,NaN,0.044300,-0.03200,-0.07060,Mutated
S099,0.20300,-0.9010,-0.30900,-0.5990,NaN,-0.241000,-0.05750,-0.19700,Mutated
S100,-0.55500,-1.2300,-0.49000,-0.7020,NaN,-0.323000,-0.43700,-0.38000,Mutated
S101,0.40500,-0.0359,0.09520,0.2510,NaN,0.064400,0.23100,-0.21700,Wildtype
S102,-0.26500,0.9150,0.04850,-1.0200,NaN,-0.277000,-1.06000,-0.06550,Wildtype
S103,-0.12100,0.0943,0.04440,0.0170,NaN,-0.081200,-0.17500,-0.16200,Wildtype

In [ ]:
results = ut.wrap_ttest()

In [22]:
help(ut.wrap_ttest)

Help on function wrap_ttest in module cptac.utils:

wrap_ttest(df, label_column, comparison_columns, alpha=0.05, verbose=False)